Repository kubernetes-sigs/ip-masq-agent, pull requests merged in 2019-05, with the labels that each got.

#33 Add support to ip-masq-agent to avoid masquerading any RFC reserved range by default
  README.md
  cmd/ip-masq-agent/ip-masq-agent.go
  cmd/ip-masq-agent/ip-masq-agent_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#36 push a multi-arch image
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#37 use capabilities instead of privileged
  ip-masq-agent.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#38 correct base-images
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#39 just use ParseCIDR to validate CIDRs instead of regex
  cmd/ip-masq-agent/ip-masq-agent.go
  cmd/ip-masq-agent/ip-masq-agent_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#40 Add 198.51.100.0/24 to default non-masq IP ranges.
  README.md
  cmd/ip-masq-agent/ip-masq-agent.go
  cmd/ip-masq-agent/ip-masq-agent_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#41 Push to k8s staging registry
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS
