Repository kubernetes-sigs/ip-masq-agent, pull requests merged in 2024-10, with the labels that each got.

#161 Implement pkg/interval in preparation for --to-ports
  go.mod
  pkg/interval/interval.go
  pkg/interval/interval_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#162 Implement --to-ports flag to specify explicit masquerading to-ports
  cmd/ip-masq-agent/ip-masq-agent.go
  cmd/ip-masq-agent/ip-masq-agent_test.go
Labels: cncf-cla: yes, lgtm, approved, size/L

#163 Update README.md for --random-fully and --to-ports flags
  README.md
Labels: cncf-cla: yes, size/S, lgtm, approved

#164 Log generated iptables rules too in addition to the original config file
  cmd/ip-masq-agent/ip-masq-agent.go
  cmd/ip-masq-agent/ip-masq-agent_test.go
  vendor/k8s.io/component-base/logs/logreduction/logreduction.go
  vendor/modules.txt
Labels: cncf-cla: yes, lgtm, approved, size/L

#165 Don't set --random-fully if it's not supported even if the flag is true
  cmd/ip-masq-agent/ip-masq-agent.go
  cmd/ip-masq-agent/ip-masq-agent_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#167 Bump base image to distroless-iptables:v0.6.4
  Makefile
Labels: cncf-cla: yes, size/XS, approved
